### ISSUE TITLE
The location map is not going to work any more

### ISSUE THREAD

**Issue by ls6** [jweslley/hugo-conference#2]
Google now requires a Google Maps JavaScript API Key :(
Not a big deal to get one but without it the map will not work.

Thanks for this project, it's been a great help :)

P.S. I've submitted a similar issue to `braziljs/conf-boilerplate`

**Comment by tejaycar** [comment]
@ls6 I know how to get the api key, but I have no idea how to make my project use it.  Any idea how to utilize it within this project?

**Comment by ls6** [comment]
Yes :)

In the `layouts/index.html` file change line `46` from:
`<script src="https://maps.google.com/maps/api/js?sensor=false"></script>`
to
`<script src="https://maps.google.com/maps/api/js?key=YOUR_KEY"></script>`

Good luck with your conference 👍

**Comment by jweslley** [comment]
Thanks @ls6

**Comment by tejaycar** [comment]
You both rock.  thanks a bunch.  Thanks to this project I got my first website in 15 years up and running in 2.5 hours, and it looks WAY better than I could have done myself.  It was a little funny.  I run cloud systems all day long and can run with the best of them, but when it came to actually authoring a website... let's just say my ignorance of web became very apparent very quickly.
