### ISSUE TITLE
Conference Demo on Hugo website contains 3rd party tracking

### ISSUE THREAD

**Issue by onedrawingperday** [jweslley/hugo-conference#5]
Hello again @jweslley 

I am one of the maintainers of the [Hugo Themes](https://github.com/gohugoio/hugoThemes/) repository.

Recently I audited the Hugo Themes website and it has [come to my attention](https://github.com/gohugoio/hugoThemes/issues/535) that your theme's demo has third party tracking enabled.

```
     \hugo-conference\exampleSite\config.yml
        GoogleAnalytics: "UA-9232216-1"
```

To fix this issue please leave the above parameter blank i.e.

```
     \hugo-conference\exampleSite\config.yml
        GoogleAnalytics: ""
```

Once you look into this please let me know.

Thank you!

**Comment by jweslley** [comment]
@onedrawingperday  Thanks for notice it!
